package com.adscore.signature.v5.utils;

public enum Base64Format {
    BASE64_VARIANT_ORIGINAL,
    BASE64_VARIANT_ORIGINAL_NO_PADDING,
    BASE64_VARIANT_URLSAFE,
    BASE64_VARIANT_URLSAFE_NO_PADDING
}
